index:
  path: /{_locale}
  controller: App\Controller\TechNews\IndexController::index
  defaults: { _locale: '%locale%' }
  requirements:
    _locale: en|fr

# Le RedirectController va effectuer une redirection sans avoir à passer par un controller personnalisé.
accueil:
  path:
    en: /home
    fr: /accueil
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: index
    permanent: true

# Permet d'éviter la création d'un controller personnalisé pour nos pages statiques. Contact, Présentation, Mentions légales...
mentions_legales:
  path:
    en: /legal-mentions
    fr: /mentions-legales
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/mentionslegales.html.twig